defaults:
  - polygraph_eval_medquad_default_instruct
  - top1_processing
  - _self_

experiment_name: medquad_empirical_baselines

description: "Provide the answer for the following medical question."
few_shot_prompt: "Question: {question}\nAnswer: {answer}"
prompt: "Question: {question}\nAnswer: {answer}"

max_new_tokens: 128
generation_params:
  generate_until:
    - "\n"

use_seq_ue: true
include_whitebox_ue: false
additional_estimators: 
  - module: lm_polygraph.estimators.semantic_entropy
    class_name: SemanticEntropy
    kwargs:
      class_probability_estimation: frequency
  - module: lm_polygraph.estimators.p_true_empirical
    class_name: PTrueEmpirical
    kwargs: {}
  - module: lm_polygraph.estimators.label_prob
    class_name: LabelProb
    kwargs: {}
