cd ../
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_coqa_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_sciq_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_mmlu_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=1000 subsample_eval_dataset=-1 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_triviaqa_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
# openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_truthfulqa_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
# wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_gsm8k_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=1500 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
# openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_xsum_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
# wait
# openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_samsum_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
# wait
# openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_cnn_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_medquad_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait
openai_http_proxy_url=socks5://ylxfkjoj-2:47pjy4g8mzd0@p.webshare.io:80 OPENAI_API_KEY=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 CUDA_VISIBLE_DEVICES=0,1 HYDRA_CONFIG=./configs/instruct/polygraph_eval_pubmedqa_empirical_baselines.yaml python run_polygraph_blackbox.py model=gpt-4o-mini ignore_exceptions=False batch_size=1 subsample_train_dataset=2000 subsample_background_train_dataset=1000 subsample_eval_dataset=2000 cache_path=./workdir/output_proxy_1 +metric_thrs="[0.3]" +generation_params.samples_n=5 +run_proposed_methods=True +run_layerwise_methods=False +clean_md_device=cuda +md_device=cuda +run_eigenscore=False use_density_based_ue=True
wait

