cd ../../lm-polygraph
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-7b-v1.5 &
CUDA_VISIBLE_DEVICES=1 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-7b-v1.5 &
CUDA_VISIBLE_DEVICES=2 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-7b-v1.5 &
CUDA_VISIBLE_DEVICES=3 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-7b-v1.5 &
CUDA_VISIBLE_DEVICES=4 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=alpindale/Mistral-7B-v0.2-hf +allow_newlines=False &
CUDA_VISIBLE_DEVICES=5 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=alpindale/Mistral-7B-v0.2-hf +allow_newlines=False &
CUDA_VISIBLE_DEVICES=6 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=alpindale/Mistral-7B-v0.2-hf +allow_newlines=False &
CUDA_VISIBLE_DEVICES=7 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=alpindale/Mistral-7B-v0.2-hf +allow_newlines=False
wait
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-1_6b &
CUDA_VISIBLE_DEVICES=1 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-1_6b &
CUDA_VISIBLE_DEVICES=2 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-1_6b &
CUDA_VISIBLE_DEVICES=3 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-1_6b &
CUDA_VISIBLE_DEVICES=4 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=meta-llama/Llama-2-7b-chat-hf &
CUDA_VISIBLE_DEVICES=5 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=meta-llama/Llama-2-7b-chat-hf &
CUDA_VISIBLE_DEVICES=6 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=meta-llama/Llama-2-7b-chat-hf &
CUDA_VISIBLE_DEVICES=7 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=meta-llama/Llama-2-7b-chat-hf
wait
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-12b &
CUDA_VISIBLE_DEVICES=1 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-12b &
CUDA_VISIBLE_DEVICES=2 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-12b &
CUDA_VISIBLE_DEVICES=3 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=stabilityai/stablelm-2-12b &
CUDA_VISIBLE_DEVICES=4 HYDRA_CONFIG=../examples/configs/polygraph_eval_coqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-13b-v1.5 &
CUDA_VISIBLE_DEVICES=5 HYDRA_CONFIG=../examples/configs/polygraph_eval_sciq.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-13b-v1.5 &
CUDA_VISIBLE_DEVICES=6 HYDRA_CONFIG=../examples/configs/polygraph_eval_triviaqa.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-13b-v1.5 &
CUDA_VISIBLE_DEVICES=7 HYDRA_CONFIG=../examples/configs/polygraph_eval_mmlu.yaml python ./scripts/polygraph_eval device=cuda:0 ignore_exceptions=False use_density_based_ue=True batch_size=1 subsample_train_dataset=5000 subsample_background_train_dataset=2000 subsample_eval_dataset=2000 model=lmsys/vicuna-13b-v1.5
wait